# Generated by Django 5.2 on 2025-05-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_phonecontact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('user', 'placedDate')},
        ),
        migrations.AlterField(
            model_name='order',
            name='phoneContact',
            field=models.IntegerField(default=0),
        ),
    ]
