# Generated by Django 5.2 on 2025-05-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_options_alter_order_phonecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
