# Generated by Django 5.2 on 2025-05-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_placeddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='productName',
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(unique_for_date=models.DateTimeField(auto_now_add=True)),
        ),
    ]
