# Generated by Django 5.2 on 2025-05-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_productname_alter_order_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='productOrdered',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
