# Generated by Django 5.2 on 2025-05-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_productordered_order_ordernum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderNum',
            field=models.CharField(default='86411', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='placedDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(unique_for_date=models.DateField(auto_now_add=True)),
        ),
    ]
