# Generated by Django 5.2 on 2025-05-13 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_ordernum_alter_order_placeddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderNum',
            field=models.CharField(default='76253', max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='placedDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(unique_for_date=models.DateField(default=django.utils.timezone.now)),
        ),
    ]
