# Generated by Django 5.2 on 2025-05-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_ordernum_alter_order_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderNum',
            field=models.CharField(default='77467', max_length=150),
        ),
    ]
