# Generated by Django 5.2 on 2025-05-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_ordernum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderNum',
            field=models.CharField(default='79792', max_length=150),
        ),
    ]
