# Generated by Django 5.2 on 2025-05-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_ordernum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderNum',
            field=models.CharField(default='51199', max_length=150),
        ),
    ]
