# Generated by Django 5.2 on 2025-05-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_order_ordernum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderNum',
            field=models.CharField(default='52423', max_length=150),
        ),
    ]
