# Generated by Django 5.2 on 2025-05-18 11:07

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_ordernum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderNum',
            field=models.CharField(default=order.models.generate_order_number, max_length=150),
        ),
    ]
