# Generated by Django 5.1.7 on 2025-03-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='page',
            field=models.SlugField(default=''),
        ),
    ]
