# Generated by Django 5.2 on 2025-05-05 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_post', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='page',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
