# Generated by Django 5.2 on 2025-05-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_post', '0005_alter_product_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='page',
            new_name='slugpage',
        ),
    ]
