# Generated by Django 5.2 on 2025-05-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_post', '0006_rename_page_product_slugpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slugpage',
            new_name='slug',
        ),
    ]
