# Generated by Django 5.2 on 2025-05-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_post', '0009_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
