# Generated by Django 5.2 on 2025-05-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_post', '0010_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbl6l7otaJhyzxtFkUxzrm5zY8xcgtKNdtbQ&s', max_length=255),
        ),
    ]
