# Generated by Django 5.2 on 2025-05-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_post', '0015_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-avg_rating', 'price']},
        ),
    ]
