# Generated by Django 5.2 on 2025-05-18 13:30

import cloudinary.models
import product_post.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_post', '0016_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[product_post.models.file_validation], verbose_name='image'),
        ),
    ]
