# Generated by Django 5.1.7 on 2025-03-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storefront',
            name='slugpage',
            field=models.SlugField(default=''),
        ),
    ]
