# Generated by Django 5.2 on 2025-05-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_alter_storefront_slugpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storefront',
            old_name='slugpage',
            new_name='slug',
        ),
    ]
